name: focale-amd64-ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image for Ubuntu 20.04
      run: |
        docker build -f Dockerfile -t alexbocharov/github-runner:focal-dev .
      working-directory: src/focal/amd64/