name: focal-amd64-ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  GITHUB_RUNNER_VERSION: latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image for Ubuntu 20.04 LTS amd64
      run: |
        GITHUB_RUNNER_VERSION=$(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep tag_name | sed -E 's/.*"v([^"]+)".*/\1/') /
        && docker build -f Dockerfile -t alexbocharov/github-runner:${GITHUB_RUNNER_VERSION}-focal .
      working-directory: ./src/focal/amd64/